[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=44.0.0",
    "scrapy>=2.12.0",
    "twisted>=24.11.0",
]
